# Edit this if you want properties that are common to all application configurations.

# At start up, the system will load:
#  config/Common.properties, as a default to
#  config/<command line-selected or user-selected application configuration> (e.g., TestHub.properties)

device.vendorName       = BSC
device.vendorIdentifier = 555
device.namePrefix       = BSC-

