# Webinar 2 demo setup

common.mainClass     = dev.bscs.bacnet.applications.TestRouter
common.title         = SC-IP
device.instance      = 555002
device.uuid          = c673e790-c80d-49c7-88c0-000000555002

app.scNetworkNumber   = 5502
sc.primaryHubURI      = wss://192.168.1.98:4444
sc.hubFunctionEnable  = true
sc.hubFunctionBindURI = wss://192.168.1.98:4444
sc.vmac               = 000000000021

app.ipNetworkNumber   = 5503
ip.bindAddress        = 192.168.1.98
ip.bindPort           = 47808

#################################################################

#### Device Properties ####
device.description    = A Really Great Router!
device.modelName      = BSC Router IP-SC 
device.namePrefix     = BSCRouter
device.dccPassword    = dcc-me-now
device.reinitPassword = reinit-me-now

#### SC Properties ####
sc.directConnectEnable      = false
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestRouter.key
sc.operationalCertificate   = config/TestRouter.pem
sc.caCertificates           = config/TestSigningCertificate.pem
