#### Test Environment ####
x-sc-host       = 127.0.0.1
x-ip-host-left  = 192.168.1.98
x-ip-host-right = 192.168.168.223
#x-sc-host       = 192.168.1.173
#x-ip-host-left  = 192.168.1.111
#x-ip-host-right = 192.168.1.112

#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestRouters

#### Application Properties ####
app.leftIPNetworkNumber  = 55501
app.scNetworkNumber      = 55502
app.rightIPNetworkNumber = 55503
# these are overrides for the right router
# everything else, like sc.primaryHubURI, is shared between left and right
app.right.ip.bindAddress             = ${x-ip-host-right}
app.right.ip.bindPort                = 47808
app.right.device.instance            = 777002
app.right.device.uuid                = c673e790-c80d-49c7-88c0-131313131313
app.right.sc.vmac                    = 131313131313
app.right.sc.hubFunctionEnable       = false
app.right.sc.hubFunctionBindURI      =
app.right.sc.directConnectEnable     = false
app.right.sc.directConnectBindURI    =
app.right.sc.directConnectAcceptURIs =

#### IPv4 Datalink Properties ####
# these are for the left router
ip.bindAddress        = ${x-ip-host-left}
ip.bindPort           = 47808

#### Device Properties ####
# these are for the left router
device.instance       = 777001
device.description    = A Really Great Twin!
device.modelName      = BSC Router IP-SC 
device.namePrefix     = BSCRouter
device.uuid           = c673e790-c80d-49c7-88c0-121212121212

#### SC Properties ####
# these are for the left router
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           = wss://${x-sc-host}:4444
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = true
sc.directConnectBindURI     = wss://${x-sc-host}:4445
sc.directConnectAcceptURIs  = wss://${x-sc-host}:4445
sc.vmac                     = 121212121212
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestRouter.key
sc.operationalCertificate   = config/TestRouter.pem
sc.caCertificates           = config/TestSigningCertificate.pem
