#### Test Environment ####
x-sc-host = 127.0.0.1
x-ip-host = 192.168.1.98

# testing properties - reset when done.
#sc.initiatingHeartbeatTimeout  =  5000
#sc.acceptingHeartbeatTimeout   = 11000


#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestCombo
stack.debugDisplayAPDUs = true
#common.shell = console

### Application Properties ####
app.ipNetworkNumber  = 55501
app.scNetworkNumber  = 55502

#### IPv4 Datalink Properties ####
ip.bindAddress        = ${x-ip-host}
ip.bindPort           = 47808

app.numberOfNodes = 2
app.nodesBaseVMAC = 777777777001
app.nodesBaseDeviceInstance = 777001
# the port number is incremented and appended to end of the strings
# only supports one "accept" URI but doesn't assume its the same as the bind
app.nodesBaseDirectConnectPort       = 4447
app.nodesBaseDirectConnectBindURI    = wss://${x-sc-host}:
app.nodesBaseDirectConnectAcceptURI = wss://${x-sc-host}:


# These are for the primary hub device
device.instance             = 555001
device.description          = A Really Great Hub!
device.modelName            = BSC Hub Model 9000
device.namePrefix           = Hub-
device.uuid                 = 67258ee1-a98c-44f2-8c4a-111111111111

# These get replaced in the failover hub (the rest of the properties are shared)
app.failover.device.instance            = 555002
app.failover.device.uuid                = 4e7b1094-93ad-4d73-924a-222222222222
app.failover.sc.vmac                    = 222222222222
app.failover.sc.hubFunctionBindURI      = wss://${x-sc-host}:4444
app.failover.sc.directConnectEnable     = true
app.failover.sc.directConnectBindURI    = wss://${x-sc-host}:4446
app.failover.sc.directConnectAcceptURIs = wss://${x-sc-host}:4446

#### SC Properties ####
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           = wss://${x-sc-host}:4444
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = true
sc.directConnectBindURI     = wss://${x-sc-host}:4445
sc.directConnectAcceptURIs  = wss://${x-sc-host}:4445
sc.vmac                     = 111111111111
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestHubs.key
sc.operationalCertificate   = config/TestHubs.pem
sc.caCertificates           = config/TestSigningCertificate.pem
