#### Test Environment ####
x-sc-host = 127.0.0.1
#x-sc-host = 192.168.1.147
#x-sc-host = 192.168.1.173

#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestHubs

### Application Properties ####
# These get replaced in the failover hub (the rest of the properties are shared)
app.failover.device.instance            = 555002
app.failover.device.uuid                = 4e7b1094-93ad-4d73-924a-222222222222
app.failover.sc.vmac                    = 222222222222
app.failover.sc.hubFunctionBindURI      = wss://${x-sc-host}:4444
app.failover.sc.directConnectEnable     = true
app.failover.sc.directConnectBindURI    = wss://${x-sc-host}:4446
app.failover.sc.directConnectAcceptURIs = wss://${x-sc-host}:4446

#### Device Object Properties ####
# These are for the primary hub device
device.instance             = 555001
device.description          = A Really Great Hub!
device.modelName            = BSC Hub Model 9000
device.namePrefix           = BSCHub
device.uuid                 = 67258ee1-a98c-44f2-8c4a-111111111111


#### SC Properties ####
# These are for the primary hub datalink
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           = wss://${x-sc-host}:4444
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = true
sc.directConnectBindURI     = wss://${x-sc-host}:4445
sc.directConnectAcceptURIs  = wss://${x-sc-host}:4445
sc.vmac                     = 111111111111
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestHubs.key
sc.operationalCertificate   = config/TestHubs.pem
sc.caCertificates           = config/TestSigningCertificate.pem
