#### test environment ####
x-ip-host = 192.168.1.98
#x-ip-host = 192.168.1.111

#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestIPDevice

### Application Properties ####

#### IP Properties ####
ip.bindAddress      = ${x-ip-host}
ip.bindPort         = 47808

#### Device Object Properties ####
device.instance     = 555005
device.description  = A Really Great IP Device!
device.modelName    = IP Device Model 3000
device.namePrefix   = BSIP
