// Copyright, distribution, and usage are defined by the top level LICENSE file.
package dev.bscs.bacnet.stack.constants;

public class ErrorCode {

    public static final int INVALID_MESSAGE_IN_THIS_STATE           = 1058;  // not in the standard
    public static final int INVALID_MESSAGE_ID                      = 1059;  // not in the standard
    public static final int OTHER 									= 0;
    public static final int CONFIGURATION_IN_PROGRESS 				= 2;
    public static final int DEVICE_BUSY 							= 3;
    public static final int DYNAMIC_CREATION_NOT_SUPPORTED			= 4;
    public static final int FILE_ACCESS_DENIED						= 5;
    public static final int INCONSISTENT_PARAMETERS 				= 7;
    public static final int INCONSISTENT_SELECTION_CRITERION 		= 8;
    public static final int INVALID_DATA_TYPE 						= 9;
    public static final int INVALID_FILE_ACCESS_METHOD				= 10;
    public static final int INVALID_FILE_START_POSITION				= 11;
    public static final int INVALID_PARAMETER_DATA_TYPE  			= 13;
    public static final int INVALID_TIMESTAMP						= 14;
    public static final int MISSING_REQUIRED_PARAMETER  			= 16;
    public static final int NO_OBJECTS_OF_SPECIFIED_TYPE 			= 17;
    public static final int NO_SPACE_FOR_OBJECT 					= 18;
    public static final int NO_SPACE_TO_ADD_LIST_ELEMENT			= 19;
    public static final int NO_SPACE_TO_WRITE_PROPERTY				= 20;
    public static final int NO_VT_SESSIONS_AVAILABLE 				= 21;
    public static final int PROPERTY_IS_NOT_A_LIST					= 22;
    public static final int OBJECT_DELETION_NOT_PERMITTED			= 23;
    public static final int OBJECT_IDENTIFIER_ALREADY_EXISTS		= 24;
    public static final int OPERATIONAL_PROBLEM 					= 25;
    public static final int PASSWORD_FAILURE						= 26;
    public static final int READ_ACCESS_DENIED 						= 27;
    public static final int SERVICE_REQUEST_DENIED 					= 29;
    public static final int TIMEOUT									= 30;
    public static final int UNKNOWN_OBJECT 							= 31;
    public static final int UNKNOWN_PROPERTY 						= 32;
    public static final int UNKNOWN_VT_CLASS 						= 34;
    public static final int UNKNOWN_VT_SESSION 						= 35;
    public static final int UNSUPPORTED_OBJECT_TYPE 				= 36;
    public static final int VALUE_OUT_OF_RANGE						= 37;
    public static final int VT_SESSION_ALREADY_CLOSED 				= 38;
    public static final int VT_SESSION_TERMINATION_FAILURE			= 39;
    public static final int WRITE_ACCESS_DENIED 					= 40;
    public static final int CHARACTER_SET_NOT_SUPPORTED				= 41;
    public static final int INVALID_ARRAY_INDEX						= 42;
    public static final int COV_SUBSCRIPTION_FAILED					= 43;
    public static final int NOT_COV_PROPERTY						= 44;
    public static final int OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED	= 45;
    public static final int INVALID_CONFIGURATION_DATA				= 46;
    public static final int DATATYPE_NOT_SUPPORTED					= 47;
    public static final int DUPLICATE_NAME							= 48;
    public static final int DUPLICATE_OBJECT_ID						= 49;
    public static final int PROPERTY_IS_NOT_AN_ARRAY				= 50;
    public static final int ABORT_BUFFER_OVERFLOW					= 51;
    public static final int ABORT_INVALID_APDU_IN_THIS_STATE		= 52;
    public static final int ABORT_PREEMPTED_BY_HIGHER_PRIORITY_TASK	= 53;
    public static final int ABORT_SEGMENTATION_NOT_SUPPORTED		= 54;
    public static final int ABORT_PROPRIETARY						= 55;
    public static final int ABORT_OTHER								= 56;
    public static final int INVALID_TAG								= 57;
    public static final int NETWORK_DOWN							= 58;
    public static final int REJECT_BUFFER_OVERFLOW					= 59;
    public static final int REJECT_INCONSISTENT_PARAMETERS			= 60;
    public static final int REJECT_INVALID_PARAMETER_DATA_TYPE		= 61;
    public static final int REJECT_INVALID_TAG						= 62;
    public static final int REJECT_MISSING_REQUIRED_PARAMETER		= 63;
    public static final int REJECT_PARAMETER_OUT_OF_RANGE			= 64;
    public static final int REJECT_TOO_MANY_ARGUMENTS				= 65;
    public static final int REJECT_UNDEFINED_ENUMERATION			= 66;
    public static final int REJECT_UNRECOGNIZED_SERVICE				= 67;
    public static final int REJECT_PROPRIETARY						= 68;
    public static final int REJECT_OTHER							= 69;
    public static final int UNKNOWN_DEVICE							= 70;
    public static final int UNKNOWN_ROUTE							= 71;
    public static final int VALUE_NOT_INITIALIZED					= 72;
    public static final int INVALID_EVENT_STATE						= 73;
    public static final int NO_ALARM_CONFIGURED						= 74;
    public static final int LOG_BUFFER_FULL							= 75;
    public static final int LOGGED_VALUE_PURGED						= 76;
    public static final int NO_PROPERTY_SPECIFIED					= 77;
    public static final int NOT_CONFIGURED_FOR_TRIGGERED_LOGGING	= 78;
    public static final int UNKNOWN_SUBSCRIPTION					= 79;
    public static final int PARAMETER_OUT_OF_RANGE					= 80;
    public static final int LIST_ELEMENT_NOT_FOUND					= 81;
    public static final int BUSY									= 82;
    public static final int COMMUNICATION_DISABLED					= 83;
    public static final int SUCCESS									= 84;
    public static final int ACCESS_DENIED							= 85;
    public static final int BAD_DESTINATION_ADDRESS					= 86;
    public static final int BAD_DESTINATION_DEVICE_ID				= 87;
    public static final int BAD_SIGNATURE							= 88;
    public static final int BAD_SOURCE_ADDRESS						= 89;
    public static final int BAD_TIMESTAMP							= 90;
    public static final int CANNOT_USE_KEY							= 91;
    public static final int CANNOT_VERIFY_MESSAGE_ID				= 92;
    public static final int CORRECT_KEY_REVISION					= 93;
    public static final int DESTINATION_DEVICE_ID_REQUIRED			= 94;
    public static final int DUPLICATE_MESSAGE						= 95;
    public static final int ENCRYPTION_NOT_CONFIGURED				= 96;
    public static final int ENCRYPTION_REQUIRED						= 97;
    public static final int INCORRECT_KEY							= 98;
    public static final int INVALID_KEY_DATA						= 99;
    public static final int KEY_UPDATE_IN_PROGRESS					= 100;
    public static final int MALFORMED_MESSAGE						= 101;
    public static final int NOT_KEY_SERVER							= 102;
    public static final int SECURITY_NOT_CONFIGURED					= 103;
    public static final int SOURCE_SECURITY_REQUIRED				= 104;
    public static final int TOO_MANY_KEYS							= 105;
    public static final int UNKNOWN_AUTHENTICATION_TYPE				= 106;
    public static final int UNKNOWN_KEY								= 107;
    public static final int UNKNOWN_KEY_REVISION					= 108;
    public static final int UNKNOWN_SOURCE_MESSAGE					= 109;
    public static final int NOT_ROUTER_TO_DNET						= 110;
    public static final int ROUTER_BUSY								= 111;
    public static final int UNKNOWN_NETWORK_MESSAGE					= 112;
    public static final int MESSAGE_TOO_LONG						= 113;
    public static final int SECURITY_ERROR							= 114;
    public static final int ADDRESSING_ERROR						= 115;
    public static final int WRITE_BDT_FAILED						= 116;
    public static final int READ_BDT_FAILED							= 117;
    public static final int REGISTER_FOREIGN_DEVICE_FAILED			= 118;
    public static final int READ_FDT_FAILED							= 119;
    public static final int DELETE_FDT_ENTRY_FAILED					= 120;
    public static final int DISTRIBUTE_BROADCAST_FAILED				= 121;
    public static final int UNKNOWN_FILE_SIZE						= 122;
    public static final int ABORT_APDU_TOO_LONG						= 123;
    public static final int ABORT_APPLICATION_EXCEEDED_REPLY_TIME	= 124;
    public static final int ABORT_OUT_OF_RESOURCES					= 125;
    public static final int ABORT_TSM_TIMEOUT						= 126;
    public static final int ABORT_WINDOW_SIZE_OUT_OF_RANGE			= 127;
    public static final int FILE_FULL								= 128;
    public static final int INCONSISTENT_CONFIGURATION				= 129;
    public static final int INCONSISTENT_OBJECT_TYPE				= 130;
    public static final int INTERNAL_ERROR							= 131;
    public static final int NOT_CONFIGURED							= 132;
    public static final int OUT_OF_MEMORY							= 133;
    public static final int VALUE_TOO_LONG							= 134;
    public static final int ABORT_INSUFFICIENT_SECURITY				= 135;
    public static final int ABORT_SECURITY_ERROR					= 136;
    public static final int DUPLICATE_ENTRY 						= 137;
    public static final int INVALID_VALUE_IN_THIS_STATE				= 138;
    // added for BACnet/SC
    public static final int BVLC_FUNCTION_UNKNOWN                   = 143;
    public static final int BVLC_PROPRIETARY_FUNCTION_UNKNOWN       = 144;
    public static final int HEADER_ENCODING_ERROR                   = 145;
    public static final int HEADER_NOT_UNDERSTOOD                   = 146;
    public static final int MESSAGE_INCOMPLETE                      = 147;
    public static final int NOT_A_BACNET_SC_HUB                     = 148;
    public static final int PAYLOAD_EXPECTED                        = 149;
    public static final int UNEXPECTED_DATA                         = 150;
    public static final int NODE_DUPLICATE_VMAC                     = 151;
    public static final int HTTP_UNEXPECTED_RESPONSE_CODE           = 152;
    public static final int HTTP_NO_UPGRADE                         = 153;
    public static final int HTTP_RESOURCE_NOT_LOCAL                 = 154;
    public static final int HTTP_PROXY_AUTHENTICATION_FAILED        = 155;
    public static final int HTTP_RESPONSE_TIMEOUT                   = 156;
    public static final int HTTP_RESPONSE_SYNTAX_ERROR              = 157;
    public static final int HTTP_RESPONSE_VALUE_ERROR               = 158;
    public static final int HTTP_RESPONSE_MISSING_HEADER            = 159;
    public static final int HTTP_WEBSOCKET_HEADER_ERROR             = 160;
    public static final int HTTP_UPGRADE_REQUIRED                   = 161;
    public static final int HTTP_UPGRADE_ERROR                      = 162;
    public static final int HTTP_TEMPORARY_UNAVAILABLE              = 163;
    public static final int HTTP_NOT_A_SERVER                       = 164;
    public static final int HTTP_ERROR                              = 165;
    public static final int WEBSOCKET_SCHEME_NOT_SUPPORTED          = 166;
    public static final int WEBSOCKET_UNKNOWN_CONTROL_MESSAGE       = 167;
    public static final int WEBSOCKET_CLOSE_ERROR                   = 168;
    public static final int WEBSOCKET_CLOSED_BY_PEER                = 169;
    public static final int WEBSOCKET_ENDPOINT_LEAVES               = 170;
    public static final int WEBSOCKET_PROTOCOL_ERROR                = 171;
    public static final int WEBSOCKET_DATA_NOT_ACCEPTED             = 172;
    public static final int WEBSOCKET_CLOSED_ABNORMALLY             = 173;
    public static final int WEBSOCKET_DATA_INCONSISTENT             = 174;
    public static final int WEBSOCKET_DATA_AGAINST_POLICY           = 175;
    public static final int WEBSOCKET_FRAME_TOO_LONG                = 176;
    public static final int WEBSOCKET_EXTENSION_MISSING             = 177;
    public static final int WEBSOCKET_REQUEST_UNAVAILABLE           = 178;
    public static final int WEBSOCKET_ERROR                         = 179;
    public static final int TLS_CLIENT_CERTIFICATE_ERROR            = 180;
    public static final int TLS_SERVER_CERTIFICATE_ERROR            = 181;
    public static final int TLS_CLIENT_AUTHENTICATION_FAILED        = 182;
    public static final int TLS_SERVER_AUTHENTICATION_FAILED        = 183;
    public static final int TLS_CLIENT_CERTIFICATE_EXPIRED          = 184;
    public static final int TLS_SERVER_CERTIFICATE_EXPIRED          = 185;
    public static final int TLS_CLIENT_CERTIFICATE_REVOKED          = 186;
    public static final int TLS_SERVER_CERTIFICATE_REVOKED          = 187;
    public static final int TLS_ERROR                               = 188;
    public static final int DNS_UNAVAILABLE                         = 189;
    public static final int DNS_NAME_RESOLUTION_FAILED              = 190;
    public static final int DNS_RESOLVER_FAILURE                    = 191;
    public static final int DNS_ERROR                               = 192;
    public static final int TCP_CONNECT_TIMEOUT                     = 193;
    public static final int TCP_CONNECTION_REFUSED                  = 194;
    public static final int TCP_CLOSED_BY_LOCAL                     = 195;
    public static final int TCP_CLOSED_OTHER                        = 196;
    public static final int TCP_OTHER_ERROR                         = 197;
    public static final int IP_ADDRESS_NOT_REACHABLE                = 198;
    public static final int IP_ERROR                                = 199;

    public static String toString(int code) {
        switch (code) {
            case INVALID_MESSAGE_IN_THIS_STATE:           return "INVALID_MESSAGE_IN_THIS_STATE";
            case INVALID_MESSAGE_ID:                      return "INVALID_MESSAGE_ID";
            case OTHER:                                   return "OTHER";
            case CONFIGURATION_IN_PROGRESS :              return "CONFIGURATION_IN_PROGRESS";
            case DEVICE_BUSY :                            return "DEVICE_BUSY";
            case DYNAMIC_CREATION_NOT_SUPPORTED:          return "DYNAMIC_CREATION_NOT_SUPPORTED";
            case FILE_ACCESS_DENIED:                      return "FILE_ACCESS_DENIED";
            case INCONSISTENT_PARAMETERS :                return "INCONSISTENT_PARAMETERS";
            case INCONSISTENT_SELECTION_CRITERION :       return "INCONSISTENT_SELECTION_CRITERION";
            case INVALID_DATA_TYPE :                      return "INVALID_DATA_TYPE";
            case INVALID_FILE_ACCESS_METHOD:              return "INVALID_FILE_ACCESS_METHOD";
            case INVALID_FILE_START_POSITION:             return "INVALID_FILE_START_POSITION";
            case INVALID_PARAMETER_DATA_TYPE  :           return "INVALID_PARAMETER_DATA_TYPE";
            case INVALID_TIMESTAMP:                       return "INVALID_TIMESTAMP";
            case MISSING_REQUIRED_PARAMETER  :            return "MISSING_REQUIRED_PARAMETER";
            case NO_OBJECTS_OF_SPECIFIED_TYPE :           return "NO_OBJECTS_OF_SPECIFIED_TYPE";
            case NO_SPACE_FOR_OBJECT :                    return "NO_SPACE_FOR_OBJECT";
            case NO_SPACE_TO_ADD_LIST_ELEMENT:            return "NO_SPACE_TO_ADD_LIST_ELEMENT";
            case NO_SPACE_TO_WRITE_PROPERTY:              return "NO_SPACE_TO_WRITE_PROPERTY";
            case NO_VT_SESSIONS_AVAILABLE :               return "NO_VT_SESSIONS_AVAILABLE";
            case PROPERTY_IS_NOT_A_LIST:                  return "PROPERTY_IS_NOT_A_LIST";
            case OBJECT_DELETION_NOT_PERMITTED:           return "OBJECT_DELETION_NOT_PERMITTED";
            case OBJECT_IDENTIFIER_ALREADY_EXISTS:        return "OBJECT_IDENTIFIER_ALREADY_EXISTS";
            case OPERATIONAL_PROBLEM :                    return "OPERATIONAL_PROBLEM";
            case PASSWORD_FAILURE:                        return "PASSWORD_FAILURE";
            case READ_ACCESS_DENIED :                     return "READ_ACCESS_DENIED";
            case SERVICE_REQUEST_DENIED :                 return "SERVICE_REQUEST_DENIED";
            case TIMEOUT:                                 return "TIMEOUT";
            case UNKNOWN_OBJECT :                         return "UNKNOWN_OBJECT";
            case UNKNOWN_PROPERTY :                       return "UNKNOWN_PROPERTY";
            case UNKNOWN_VT_CLASS :                       return "UNKNOWN_VT_CLASS";
            case UNKNOWN_VT_SESSION :                     return "UNKNOWN_VT_SESSION";
            case UNSUPPORTED_OBJECT_TYPE :                return "UNSUPPORTED_OBJECT_TYPE";
            case VALUE_OUT_OF_RANGE:                      return "VALUE_OUT_OF_RANGE";
            case VT_SESSION_ALREADY_CLOSED :              return "VT_SESSION_ALREADY_CLOSED";
            case VT_SESSION_TERMINATION_FAILURE:          return "VT_SESSION_TERMINATION_FAILURE";
            case WRITE_ACCESS_DENIED :                    return "WRITE_ACCESS_DENIED";
            case CHARACTER_SET_NOT_SUPPORTED:             return "CHARACTER_SET_NOT_SUPPORTED";
            case INVALID_ARRAY_INDEX:                     return "INVALID_ARRAY_INDEX";
            case COV_SUBSCRIPTION_FAILED:                 return "COV_SUBSCRIPTION_FAILED";
            case NOT_COV_PROPERTY:                        return "NOT_COV_PROPERTY";
            case OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED:    return "OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED";
            case INVALID_CONFIGURATION_DATA:              return "INVALID_CONFIGURATION_DATA";
            case DATATYPE_NOT_SUPPORTED:                  return "DATATYPE_NOT_SUPPORTED";
            case DUPLICATE_NAME:                          return "DUPLICATE_NAME";
            case DUPLICATE_OBJECT_ID:                     return "DUPLICATE_OBJECT_ID";
            case PROPERTY_IS_NOT_AN_ARRAY:                return "PROPERTY_IS_NOT_AN_ARRAY";
            case ABORT_BUFFER_OVERFLOW:                   return "ABORT_BUFFER_OVERFLOW";
            case ABORT_INVALID_APDU_IN_THIS_STATE:        return "ABORT_INVALID_APDU_IN_THIS_STATE";
            case ABORT_PREEMPTED_BY_HIGHER_PRIORITY_TASK: return "ABORT_PREEMPTED_BY_HIGHER_PRIORITY_TASK";
            case ABORT_SEGMENTATION_NOT_SUPPORTED:        return "ABORT_SEGMENTATION_NOT_SUPPORTED";
            case ABORT_PROPRIETARY:                       return "ABORT_PROPRIETARY";
            case ABORT_OTHER:                             return "ABORT_OTHER";
            case INVALID_TAG:                             return "INVALID_TAG";
            case NETWORK_DOWN:                            return "NETWORK_DOWN";
            case REJECT_BUFFER_OVERFLOW:                  return "REJECT_BUFFER_OVERFLOW";
            case REJECT_INCONSISTENT_PARAMETERS:          return "REJECT_INCONSISTENT_PARAMETERS";
            case REJECT_INVALID_PARAMETER_DATA_TYPE:      return "REJECT_INVALID_PARAMETER_DATA_TYPE";
            case REJECT_INVALID_TAG:                      return "REJECT_INVALID_TAG";
            case REJECT_MISSING_REQUIRED_PARAMETER:       return "REJECT_MISSING_REQUIRED_PARAMETER";
            case REJECT_PARAMETER_OUT_OF_RANGE:           return "REJECT_PARAMETER_OUT_OF_RANGE";
            case REJECT_TOO_MANY_ARGUMENTS:               return "REJECT_TOO_MANY_ARGUMENTS";
            case REJECT_UNDEFINED_ENUMERATION:            return "REJECT_UNDEFINED_ENUMERATION";
            case REJECT_UNRECOGNIZED_SERVICE:             return "REJECT_UNRECOGNIZED_SERVICE";
            case REJECT_PROPRIETARY:                      return "REJECT_PROPRIETARY";
            case REJECT_OTHER:                            return "REJECT_OTHER";
            case UNKNOWN_DEVICE:                          return "UNKNOWN_DEVICE";
            case UNKNOWN_ROUTE:                           return "UNKNOWN_ROUTE";
            case VALUE_NOT_INITIALIZED:                   return "VALUE_NOT_INITIALIZED";
            case INVALID_EVENT_STATE:                     return "INVALID_EVENT_STATE";
            case NO_ALARM_CONFIGURED:                     return "NO_ALARM_CONFIGURED";
            case LOG_BUFFER_FULL:                         return "LOG_BUFFER_FULL";
            case LOGGED_VALUE_PURGED:                     return "LOGGED_VALUE_PURGED";
            case NO_PROPERTY_SPECIFIED:                   return "NO_PROPERTY_SPECIFIED";
            case NOT_CONFIGURED_FOR_TRIGGERED_LOGGING:    return "NOT_CONFIGURED_FOR_TRIGGERED_LOGGING";
            case UNKNOWN_SUBSCRIPTION:                    return "UNKNOWN_SUBSCRIPTION";
            case PARAMETER_OUT_OF_RANGE:                  return "PARAMETER_OUT_OF_RANGE";
            case LIST_ELEMENT_NOT_FOUND:                  return "LIST_ELEMENT_NOT_FOUND";
            case BUSY:                                    return "BUSY";
            case COMMUNICATION_DISABLED:                  return "COMMUNICATION_DISABLED";
            case SUCCESS:                                 return "SUCCESS";
            case ACCESS_DENIED:                           return "ACCESS_DENIED";
            case BAD_DESTINATION_ADDRESS:                 return "BAD_DESTINATION_ADDRESS";
            case BAD_DESTINATION_DEVICE_ID:               return "BAD_DESTINATION_DEVICE_ID";
            case BAD_SIGNATURE:                           return "BAD_SIGNATURE";
            case BAD_SOURCE_ADDRESS:                      return "BAD_SOURCE_ADDRESS";
            case BAD_TIMESTAMP:                           return "BAD_TIMESTAMP";
            case CANNOT_USE_KEY:                          return "CANNOT_USE_KEY";
            case CANNOT_VERIFY_MESSAGE_ID:                return "CANNOT_VERIFY_MESSAGE_ID";
            case CORRECT_KEY_REVISION:                    return "CORRECT_KEY_REVISION";
            case DESTINATION_DEVICE_ID_REQUIRED:          return "DESTINATION_DEVICE_ID_REQUIRED";
            case DUPLICATE_MESSAGE:                       return "DUPLICATE_MESSAGE";
            case ENCRYPTION_NOT_CONFIGURED:               return "ENCRYPTION_NOT_CONFIGURED";
            case ENCRYPTION_REQUIRED:                     return "ENCRYPTION_REQUIRED";
            case INCORRECT_KEY:                           return "INCORRECT_KEY";
            case INVALID_KEY_DATA:                        return "INVALID_KEY_DATA";
            case KEY_UPDATE_IN_PROGRESS:                  return "KEY_UPDATE_IN_PROGRESS";
            case MALFORMED_MESSAGE:                       return "MALFORMED_MESSAGE";
            case NOT_KEY_SERVER:                          return "NOT_KEY_SERVER";
            case SECURITY_NOT_CONFIGURED:                 return "SECURITY_NOT_CONFIGURED";
            case SOURCE_SECURITY_REQUIRED:                return "SOURCE_SECURITY_REQUIRED";
            case TOO_MANY_KEYS:                           return "TOO_MANY_KEYS";
            case UNKNOWN_AUTHENTICATION_TYPE:             return "UNKNOWN_AUTHENTICATION_TYPE";
            case UNKNOWN_KEY:                             return "UNKNOWN_KEY";
            case UNKNOWN_KEY_REVISION:                    return "UNKNOWN_KEY_REVISION";
            case UNKNOWN_SOURCE_MESSAGE:                  return "UNKNOWN_SOURCE_MESSAGE";
            case NOT_ROUTER_TO_DNET:                      return "NOT_ROUTER_TO_DNET";
            case ROUTER_BUSY:                             return "ROUTER_BUSY";
            case UNKNOWN_NETWORK_MESSAGE:                 return "UNKNOWN_NETWORK_MESSAGE";
            case MESSAGE_TOO_LONG:                        return "MESSAGE_TOO_LONG";
            case SECURITY_ERROR:                          return "SECURITY_ERROR";
            case ADDRESSING_ERROR:                        return "ADDRESSING_ERROR";
            case WRITE_BDT_FAILED:                        return "WRITE_BDT_FAILED";
            case READ_BDT_FAILED:                         return "READ_BDT_FAILED";
            case REGISTER_FOREIGN_DEVICE_FAILED:          return "REGISTER_FOREIGN_DEVICE_FAILED";
            case READ_FDT_FAILED:                         return "READ_FDT_FAILED";
            case DELETE_FDT_ENTRY_FAILED:                 return "DELETE_FDT_ENTRY_FAILED";
            case DISTRIBUTE_BROADCAST_FAILED:             return "DISTRIBUTE_BROADCAST_FAILED";
            case UNKNOWN_FILE_SIZE:                       return "UNKNOWN_FILE_SIZE";
            case ABORT_APDU_TOO_LONG:                     return "ABORT_APDU_TOO_LONG";
            case ABORT_APPLICATION_EXCEEDED_REPLY_TIME:   return "ABORT_APPLICATION_EXCEEDED_REPLY_TIME";
            case ABORT_OUT_OF_RESOURCES:                  return "ABORT_OUT_OF_RESOURCES";
            case ABORT_TSM_TIMEOUT:                       return "ABORT_TSM_TIMEOUT";
            case ABORT_WINDOW_SIZE_OUT_OF_RANGE:          return "ABORT_WINDOW_SIZE_OUT_OF_RANGE";
            case FILE_FULL:                               return "FILE_FULL";
            case INCONSISTENT_CONFIGURATION:              return "INCONSISTENT_CONFIGURATION";
            case INCONSISTENT_OBJECT_TYPE:                return "INCONSISTENT_OBJECT_TYPE";
            case INTERNAL_ERROR:                          return "INTERNAL_ERROR";
            case NOT_CONFIGURED:                          return "NOT_CONFIGURED";
            case OUT_OF_MEMORY:                           return "OUT_OF_MEMORY";
            case VALUE_TOO_LONG:                          return "VALUE_TOO_LONG";
            case ABORT_INSUFFICIENT_SECURITY:             return "ABORT_INSUFFICIENT_SECURITY";
            case ABORT_SECURITY_ERROR:                    return "ABORT_SECURITY_ERROR";
            case DUPLICATE_ENTRY :                        return "DUPLICATE_ENTRY";
            case INVALID_VALUE_IN_THIS_STATE:             return "INVALID_VALUE_IN_THIS_STATE";
            case BVLC_FUNCTION_UNKNOWN:                   return "BVLC_FUNCTION_UNKNOWN";
            case BVLC_PROPRIETARY_FUNCTION_UNKNOWN:       return "BVLC_PROPRIETARY_FUNCTION_UNKNOWN";
            case HEADER_ENCODING_ERROR:                   return "HEADER_ENCODING_ERROR";
            case HEADER_NOT_UNDERSTOOD:                   return "HEADER_NOT_UNDERSTOOD";
            case MESSAGE_INCOMPLETE:                      return "MESSAGE_INCOMPLETE";
            case NOT_A_BACNET_SC_HUB:                     return "NOT_A_BACNET_SC_HUB";
            case PAYLOAD_EXPECTED:                        return "PAYLOAD_EXPECTED";
            case UNEXPECTED_DATA:                         return "UNEXPECTED_DATA";
            case NODE_DUPLICATE_VMAC:                     return "NODE_DUPLICATE_VMAC";
            case HTTP_UNEXPECTED_RESPONSE_CODE:           return "HTTP_UNEXPECTED_RESPONSE_CODE";
            case HTTP_NO_UPGRADE:                         return "HTTP_NO_UPGRADE";
            case HTTP_RESOURCE_NOT_LOCAL:                 return "HTTP_RESOURCE_NOT_LOCAL";
            case HTTP_PROXY_AUTHENTICATION_FAILED:        return "HTTP_PROXY_AUTHENTICATION_FAILED";
            case HTTP_RESPONSE_TIMEOUT:                   return "HTTP_RESPONSE_TIMEOUT";
            case HTTP_RESPONSE_SYNTAX_ERROR:              return "HTTP_RESPONSE_SYNTAX_ERROR";
            case HTTP_RESPONSE_VALUE_ERROR:               return "HTTP_RESPONSE_VALUE_ERROR";
            case HTTP_RESPONSE_MISSING_HEADER:            return "HTTP_RESPONSE_MISSING_HEADER";
            case HTTP_WEBSOCKET_HEADER_ERROR:             return "HTTP_WEBSOCKET_HEADER_ERROR";
            case HTTP_UPGRADE_REQUIRED:                   return "HTTP_UPGRADE_REQUIRED";
            case HTTP_UPGRADE_ERROR:                      return "HTTP_UPGRADE_ERROR";
            case HTTP_TEMPORARY_UNAVAILABLE:              return "HTTP_TEMPORARY_UNAVAILABLE";
            case HTTP_NOT_A_SERVER:                       return "HTTP_NOT_A_SERVER";
            case HTTP_ERROR:                              return "HTTP_ERROR";
            case WEBSOCKET_SCHEME_NOT_SUPPORTED:          return "WEBSOCKET_SCHEME_NOT_SUPPORTED";
            case WEBSOCKET_UNKNOWN_CONTROL_MESSAGE:       return "WEBSOCKET_UNKNOWN_CONTROL_MESSAGE";
            case WEBSOCKET_CLOSE_ERROR:                   return "WEBSOCKET_CLOSE_ERROR";
            case WEBSOCKET_CLOSED_BY_PEER:                return "WEBSOCKET_CLOSED_BY_PEER";
            case WEBSOCKET_ENDPOINT_LEAVES:               return "WEBSOCKET_ENDPOINT_LEAVES";
            case WEBSOCKET_PROTOCOL_ERROR:                return "WEBSOCKET_PROTOCOL_ERROR";
            case WEBSOCKET_DATA_NOT_ACCEPTED:             return "WEBSOCKET_DATA_NOT_ACCEPTED";
            case WEBSOCKET_CLOSED_ABNORMALLY:             return "WEBSOCKET_CLOSED_ABNORMALLY";
            case WEBSOCKET_DATA_INCONSISTENT:             return "WEBSOCKET_DATA_INCONSISTENT";
            case WEBSOCKET_DATA_AGAINST_POLICY:           return "WEBSOCKET_DATA_AGAINST_POLICY";
            case WEBSOCKET_FRAME_TOO_LONG:                return "WEBSOCKET_FRAME_TOO_LONG";
            case WEBSOCKET_EXTENSION_MISSING:             return "WEBSOCKET_EXTENSION_MISSING";
            case WEBSOCKET_REQUEST_UNAVAILABLE:           return "WEBSOCKET_REQUEST_UNAVAILABLE";
            case WEBSOCKET_ERROR:                         return "WEBSOCKET_ERROR";
            case TLS_CLIENT_CERTIFICATE_ERROR:            return "TLS_CLIENT_CERTIFICATE_ERROR";
            case TLS_SERVER_CERTIFICATE_ERROR:            return "TLS_SERVER_CERTIFICATE_ERROR";
            case TLS_CLIENT_AUTHENTICATION_FAILED:        return "TLS_CLIENT_AUTHENTICATION_FAILED";
            case TLS_SERVER_AUTHENTICATION_FAILED:        return "TLS_SERVER_AUTHENTICATION_FAILED";
            case TLS_CLIENT_CERTIFICATE_EXPIRED:          return "TLS_CLIENT_CERTIFICATE_EXPIRED";
            case TLS_SERVER_CERTIFICATE_EXPIRED:          return "TLS_SERVER_CERTIFICATE_EXPIRED";
            case TLS_CLIENT_CERTIFICATE_REVOKED:          return "TLS_CLIENT_CERTIFICATE_REVOKED";
            case TLS_SERVER_CERTIFICATE_REVOKED:          return "TLS_SERVER_CERTIFICATE_REVOKED";
            case TLS_ERROR:                               return "TLS_ERROR";
            case DNS_UNAVAILABLE:                         return "DNS_UNAVAILABLE";
            case DNS_NAME_RESOLUTION_FAILED:              return "DNS_NAME_RESOLUTION_FAILED";
            case DNS_RESOLVER_FAILURE:                    return "DNS_RESOLVER_FAILURE";
            case DNS_ERROR:                               return "DNS_ERROR";
            case TCP_CONNECT_TIMEOUT:                     return "TCP_CONNECT_TIMEOUT";
            case TCP_CONNECTION_REFUSED:                  return "TCP_CONNECTION_REFUSED";
            case TCP_CLOSED_BY_LOCAL:                     return "TCP_CLOSED_BY_LOCAL";
            case TCP_CLOSED_OTHER:                        return "TCP_CLOSED_OTHER";
            case TCP_OTHER_ERROR:                         return "TCP_OTHER_ERROR";
            case IP_ADDRESS_NOT_REACHABLE:                return "IP_ADDRESS_NOT_REACHABLE";
            case IP_ERROR:                                return "IP_ERROR";
            default:                                      return "???";
        }
    }
}
