s1[0]="A"
s1[1]="B"
s1[image]="loriringhio97/p4"

s2[0]="C"
s2[1]="B"
s2[image]="loriringhio97/p4"


bacnetclient[0]="A"
bacnetclient[image]="loriringhio97/bacnet"
bacnetclient[shell]="/bin/sh"

bacnetserver[0]="C"
bacnetserver[image]="loriringhio97/bacnet"
bacnetserver[shell]="/bin/sh"


# wireshark[0]="A"
# wireshark[1]="B"
# wireshark[2]="C"
# wireshark[bridged]=true
# wireshark[port]="3000:3000/tcp"
# wireshark[image]="lscr.io/linuxserver/wireshark"
