#### Kathara BACnet/SC Hub + Server Device ####

x-sc-host = 200.1.1.9

#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestHub
common.shell = console
common.title = BACnetSC-Hub-Server

#### Device Object Properties ####
device.instance             = 555001
device.description          = Kathara BACnet/SC Hub Device
device.modelName            = BACnetSC Hub for Benchmark
device.namePrefix           = KTHub

#### SC Properties ####
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           =
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = false
sc.directConnectBindURI     =
sc.directConnectAcceptURIs  =
sc.vmac                     = 111111111111
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.allowPlain               = false
sc.privateKey               = config/TestHub.key
sc.operationalCertificate   = config/TestHub.pem
sc.caCertificates           = config/TestSigningCertificate.pem
