// Copyright, distribution, and usage are defined by the top level LICENSE file.
package dev.bscs.events;

/**
 * An interface for receiving {@link Event} objects, generated by asynchronous calls to {@link EventLoop#emit}, that are
 * to be processed in the main thread.
 * @author drobin
 */
public interface EventListener {
    void handleEvent(Object source, EventType eventType, Object... args);
}
