# Webinar 2 demo setup

common.mainClass    = dev.bscs.bacnet.applications.TestNode
common.commandClass = com.example.demo.DemoCommands
common.title        = Device 4
device.instance     = 777004
device.uuid         = c673e790-c80d-49c7-88c0-000000777004
sc.primaryHubURI    = wss://192.168.1.99:4443
sc.vmac             = 000000000004

##################################################################

#### Device Properties ####
device.description        = A Really Great Node!
device.modelName          = BSC Node Mark 12
device.namePrefix         = BSCNode

#### SC Properties ####
sc.hubFunctionEnable        = false
sc.directConnectEnable      = false
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestNode.key
sc.operationalCertificate   = config/TestNode.pem
sc.caCertificates           = config/TestSigningCertificate.pem
