# Webinar 2 demo setup

#### Common Properties ####
common.mainClass   = TestSCSC
common.mainScript  = scripts/TestSCSC.py
common.commandClass= com.example.demo.DemoCommands
common.title       = SC-SC
device.instance    = 555001
device.uuid        = c673e790-c80d-49c7-88c0-000000555001

# the primary hub for the left SC network is in this device
app.scNetworkNumber1        = 5501
sc.primaryHubURI            = wss://192.168.1.98:4443
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://192.168.1.98:4443
sc.vmac                     = 000000000011

# the primary hub for the right SC network is in DemoSCIP
app.scNetworkNumber2        = 5502
app.2.sc.primaryHubURI      = wss://192.168.1.98:4444
app.2.sc.hubFunctionEnable  = false
app.2.sc.hubFunctionBindURI =
app.2.sc.vmac               = 000000000012

#########################################################

#### Device Properties ####
device.description    = A Really Great Router!
device.modelName      = BSC Router IP-SC
device.namePrefix     = BSCRouter

#### SC Properties ####
sc.directConnectEnable      = false
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestRouter.key
sc.operationalCertificate   = config/TestRouter.pem
sc.caCertificates           = config/TestSigningCertificate.pem


