#### Test Environment ####
x-sc-host = 127.0.0.1
#x-sc-host = 192.168.1.173

#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestHub
#common.tlsDebug  = all

#### Device Object Properties ####
device.instance             = 555001
device.description          = A Really Great Hub!
device.modelName            = BSC Hub Model 9000
device.namePrefix           = BSCHub

#### SC Properties ####
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           = wss://${x-sc-host}:4444
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = true
sc.directConnectBindURI     = wss://${x-sc-host}:4445
sc.directConnectAcceptURIs  = http://${x-sc-host}:4445 wss://${x-sc-host}:4445 ws://${x-sc-host}:4445
sc.vmac                     = 111111111111
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestHub.key
sc.operationalCertificate   = config/TestHub.pem
sc.caCertificates           = config/TestSigningCertificate.pem
