# Copyright, distribution, and usage are defined by the top level LICENSE file.
#### Test Environment ####
x-sc-host = 127.0.0.1

#### Common Properties ####
common.mainClass   = dev.bscs.bacnet.applications.TestSCSC

#### Application Properties ####
app.scNetworkNumber1  = 55501
app.scNetworkNumber2  = 55502

#### Overrides for SC datalink 2  ###
app.2.sc.primaryHubURI      = wss://${x-sc-host}:8443
app.2.sc.hubFunctionEnable  = true
app.2.sc.hubFunctionBindURI = wss://${x-sc-host}:8443
app.2.sc.vmac               = 222222222222

#### Device Properties ####
device.instance       = 555001
device.description    = A Really Great Router!
device.modelName      = BSC Router SC-SC
device.namePrefix     = BSCRouter
device.uuid           = c673e790-c80d-49c7-88c0-98789fbfffc3

#### SC Properties ####
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = false
sc.vmac                     = 111111111111
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestRouter.key
sc.operationalCertificate   = config/TestRouter.pem
sc.caCertificates           = config/TestSigningCertificate.pem


