#### Test Environment ####
#x-sc-host = 127.0.0.1
x-sc-host = 192.168.1.98

#### Common Properties ####
common.mainClass = dev.bscs.bacnet.applications.TestNode
#common.shell=console

### Application Properties ####

#### Device Properties ####
device.instance           = 555003
device.description        = A Really Great Node!
device.modelName          = BSC Node Mark 12
device.namePrefix         = BSCNode
device.uuid               = c673e790-c80d-49c7-88c0-333333333333

#### SC Properties ####
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           = wss://${x-sc-host}:4444
sc.hubFunctionEnable        = false
sc.hubFunctionBindURI       =
sc.directConnectEnable      = true
sc.directConnectBindURI     = wss://${x-sc-host}:4001
sc.directConnectAcceptURIs  = wss://${x-sc-host}:4001
sc.vmac                     = 333333333333
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.allowPlain               = false
sc.privateKey               = config/TestNode.key
sc.operationalCertificate   = config/TestNode.pem
sc.caCertificates           = config/TestSigningCertificate.pem
