#### Test Environment ####
#x-sc-host = 127.0.0.1
x-sc-host = 192.168.1.21
x-ip-host = 192.168.1.21

#### Common Properties ####
common.mainClass   = dev.bscs.bacnet.applications.TestRouter

#### Application Properties ####
app.ipNetworkNumber  = 55501
app.scNetworkNumber  = 55502

#### IPv4 Datalink Properties ####
ip.bindAddress        = ${x-ip-host}
ip.bindPort           = 47808
#ip.foreignRefresh     = 0
#ip.foreignAddress     = 1.1.1.1
#ip.foreignPort        = 47808

#### Device Properties ####
device.instance       = 555001
device.description    = A Really Great Router!
device.modelName      = BSC Router IP-SC 
device.namePrefix     = BSRouter
device.uuid           = c673e790-c80d-49c7-88c0-98789fbfffc3

#### SC Properties ####
sc.primaryHubURI            = wss://${x-sc-host}:4443
sc.failoverHubURI           = wss://${x-sc-host}:4444
sc.hubFunctionEnable        = true
sc.hubFunctionBindURI       = wss://${x-sc-host}:4443
sc.directConnectEnable      = true
sc.directConnectBindURI     = wss://${x-sc-host}:4445
sc.directConnectAcceptURIs  = wss://${x-sc-host}:4445
sc.vmac                     = 111111111111
sc.nodeEnable               = true
sc.tlsVersion               = TLSv1.3
sc.noValidation             = false
sc.privateKey               = config/TestRouter.key
sc.operationalCertificate   = config/TestRouter.pem
sc.caCertificates           = config/TestSigningCertificate.pem
